@startuml
title 销毁
actor 处置公司人员
participant 识别界面
participant 销毁界面


处置公司人员 -> 识别界面 : 扫处置人员码登录
识别界面 -> 销毁界面 : 扫医废箱
database 服务器
服务器 -> 销毁界面 : 医废箱信息
销毁界面 -> 确认销毁 : ①核对医废箱信息正确
确认销毁 -> 服务器 : 上传数据
销毁界面 -> 异议 : ②核对医废箱信息有异议
异议 -> 提交异议 : 填写异议内容
提交异议 -> 服务器 : 上传数据

@enduml